server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:containers-us-west-111.railway.app}:${DB_PORT:7420}/${DB_NAME:railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:UIMT5PA2keGsxhT2pOk0}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate.ddl-auto: ${JPA_DDL_AUTO:update}