server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-122.railway.app:6005/railway
    username: postgres
    password: 7PvhZZxc2nItK35BIJTb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update