server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:containers-us-west-122.railway.app}:${DB_PORT:6005}/${DB_NAME:railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:7PvhZZxc2nItK35BIJTb}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate.ddl-auto: ${JPA_DDL_AUTO:update}