server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    active: dev
  banner:
    location: classpath:base/banner.txt
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#springfox:
#  documentation:
#    auto-startup: true